[package]
name = "kalshi-mdp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.23.0-beta.1" }
tokio = { version = "1.34.0", features = ["full"] }
tungstenite = "0.20.1"
url = "2.5.0"
env_logger = "0.10.1"
